sonar.projectKey=employee-management-api
sonar.projectName=Employee Management API
sonar.projectVersion=1.0.0

# Path to source directories (required)
sonar.sources=app/
# Language
sonar.language=py
sonar.python.version=3.12

# Path to test directories (optional)
sonar.tests=tests/

# Coverage reporting
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/__init__.py,alembic/**
